services:
  web:
    build: ./gadalka
    image: gadalka:1.0.0
    container_name: gadalka
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 127.0.0.1:8000:8000
    env_file:
      - ./gadalka/.env
    develop:
      # watch:
      #   - action: sync
      #     path: ./gadalka
      #     target: usr/src/app
      #   - action: rebuild
      #     path: ./gadalka/requirements.txt
    volumes:
      - ./gadalka:/usr/src/app

  db:
    image: postgres:16-alpine
    container_name: postgres
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=23789163Qw
      - POSTGRES_DB=gadalka

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@mail.ru
      - PGADMIN_DEFAULT_PASSWORD=654321Qw
    ports:
      - 8080:80
    depends_on:
      - db


volumes:
  data:
    
    
