FROM python:3.12-slim

WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y netcat-openbsd

ENV PYTHONUNBUFFERED=1

RUN pip install --upgrade pip

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN chmod +x /usr/src/app/entrypoint.prod.sh

ENTRYPOINT [ "./entrypoint.prod.sh" ]